// Code generated by "stringer -type=CallType"; DO NOT EDIT

package messages

import "fmt"

const _CallType_name = "ONE2ONEONE2MANYMANY2ONEMANY2MANY"

var _CallType_index = [...]uint8{0, 7, 15, 23, 32}

func (i CallType) String() string {
	if i < 0 || i >= CallType(len(_CallType_index)-1) {
		return fmt.Sprintf("CallType(%d)", i)
	}
	return _CallType_name[_CallType_index[i]:_CallType_index[i+1]]
}
