// Code generated by "stringer -type=MessageType"; DO NOT EDIT

package messages

import "fmt"

const _MessageType_name = "HELLOHELLO_OKDO_HAVEHAVEREQUESTRESULTLISTENSTOP_LISTEN"

var _MessageType_index = [...]uint8{0, 5, 13, 20, 24, 31, 37, 43, 54}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return fmt.Sprintf("MessageType(%d)", i)
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
