package config

import (
	"github.com/ThingiverseIO/thingiverseio/descriptor"
	"github.com/ThingiverseIO/thingiverseio/uuid"
)

// InternalConfig holds parameters generated by the library and are not intended to be user changed
type InternalConfig struct {
	Output bool
	Tags   descriptor.Tagset
	UUID   uuid.UUID
}

// NewInternalConfig creates a new internal config. A new UUID is generated by this function.
func NewInternalConfig(output bool, tags descriptor.Tagset) *InternalConfig {
	return &InternalConfig{
		Output: output,
		Tags:   tags,
		UUID:   uuid.New(),
	}
}
