// Code generated by "stringer -type=MessageType"; DO NOT EDIT

package message

import "fmt"

const _MessageType_name = "HELLOHELLOOKDOHAVEHAVECONNECTREQUESTRESULTLISTENSTOPLISTENENDREJECTMOCK"

var _MessageType_index = [...]uint8{0, 5, 12, 18, 22, 29, 36, 42, 48, 58, 61, 67, 71}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_MessageType_index)-1) {
		return fmt.Sprintf("MessageType(%d)", i)
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
