
/*
 * generated by event_generator
 *
 * DO NOT EDIT
 */

package beacon

import "github.com/joernweissenborn/eventual2go"



type SignalCompleter struct {
	*eventual2go.Completer
}

func NewSignalCompleter() *SignalCompleter {
	return &SignalCompleter{eventual2go.NewCompleter()}
}

func (c *SignalCompleter) Complete(d Signal) {
	c.Completer.Complete(d)
}

func (c *SignalCompleter) Future() *SignalFuture {
	return &SignalFuture{c.Completer.Future()}
}

type SignalFuture struct {
	*eventual2go.Future
}

func (f *SignalFuture) GetResult() Signal {
	return f.Future.GetResult().(Signal)
}

type SignalCompletionHandler func(Signal) Signal

func (ch SignalCompletionHandler) toCompletionHandler() eventual2go.CompletionHandler {
	return func(d eventual2go.Data) eventual2go.Data {
		return ch(d.(Signal))
	}
}

func (f *SignalFuture) Then(ch SignalCompletionHandler) *SignalFuture {
	return &SignalFuture{f.Future.Then(ch.toCompletionHandler())}
}

func (f *SignalFuture) AsChan() chan Signal {
	c := make(chan Signal, 1)
	cmpl := func(d chan Signal) SignalCompletionHandler {
		return func(e Signal) Signal {
			d <- e
			close(d)
			return e
		}
	}
	ecmpl := func(d chan Signal) eventual2go.ErrorHandler {
		return func(error) (eventual2go.Data, error) {
			close(d)
			return nil, nil
		}
	}
	f.Then(cmpl(c))
	f.Err(ecmpl(c))
	return c
}

type SignalStreamController struct {
	*eventual2go.StreamController
}

func NewSignalStreamController() *SignalStreamController {
	return &SignalStreamController{eventual2go.NewStreamController()}
}

func (sc *SignalStreamController) Add(d Signal) {
	sc.StreamController.Add(d)
}

func (sc *SignalStreamController) Join(s *SignalStream) {
	sc.StreamController.Join(s.Stream)
}

func (sc *SignalStreamController) JoinFuture(f *SignalFuture) {
	sc.StreamController.JoinFuture(f.Future)
}

func (sc *SignalStreamController) Stream() *SignalStream {
	return &SignalStream{sc.StreamController.Stream()}
}

type SignalStream struct {
	*eventual2go.Stream
}

type SignalSubscriber func(Signal)

func (l SignalSubscriber) toSubscriber() eventual2go.Subscriber {
	return func(d eventual2go.Data) { l(d.(Signal)) }
}

func (s *SignalStream) Listen(ss SignalSubscriber) *eventual2go.Subscription {
	return s.Stream.Listen(ss.toSubscriber())
}

type SignalFilter func(Signal) bool

func (f SignalFilter) toFilter() eventual2go.Filter {
	return func(d eventual2go.Data) bool { return f(d.(Signal)) }
}

func toSignalFilterArray(f ...SignalFilter) (filter []eventual2go.Filter){

	filter = make([]eventual2go.Filter, len(f))
	for i, el := range f {
		filter[i] = el.toFilter()
	}
	return
}

func (s *SignalStream) Where(f ...SignalFilter) *SignalStream {
	return &SignalStream{s.Stream.Where(toSignalFilterArray(f...)...)}
}

func (s *SignalStream) WhereNot(f ...SignalFilter) *SignalStream {
	return &SignalStream{s.Stream.WhereNot(toSignalFilterArray(f...)...)}
}

func (s *SignalStream) Split(f SignalFilter) (*SignalStream, *SignalStream)  {
	return s.Where(f), s.WhereNot(f)
}

func (s *SignalStream) First() *SignalFuture {
	return &SignalFuture{s.Stream.First()}
}

func (s *SignalStream) FirstWhere(f... SignalFilter) *SignalFuture {
	return &SignalFuture{s.Stream.FirstWhere(toSignalFilterArray(f...)...)}
}

func (s *SignalStream) FirstWhereNot(f ...SignalFilter) *SignalFuture {
	return &SignalFuture{s.Stream.FirstWhereNot(toSignalFilterArray(f...)...)}
}

func (s *SignalStream) AsChan() (c chan Signal) {
	c = make(chan Signal)
	s.Listen(pipeToSignalChan(c)).Closed().Then(closeSignalChan(c))
	return
}

func pipeToSignalChan(c chan Signal) SignalSubscriber {
	return func(d Signal) {
		c <- d
	}
}

func closeSignalChan(c chan Signal) eventual2go.CompletionHandler {
	return func(d eventual2go.Data) eventual2go.Data {
		close(c)
		return nil
	}
}

type SignalCollector struct {
	*eventual2go.Collector
}

func NewSignalCollector() *SignalCollector {
	return &SignalCollector{eventual2go.NewCollector()}
}

func (c *SignalCollector) Add(d Signal) {
	c.Collector.Add(d)
}

func (c *SignalCollector) AddFuture(f *SignalFuture) {
	c.Collector.Add(f.Future)
}

func (c *SignalCollector) AddStream(s *SignalStream) {
	c.Collector.AddStream(s.Stream)
}

func (c *SignalCollector) Get() Signal {
	return c.Collector.Get().(Signal)
}

func (c *SignalCollector) Preview() Signal {
	return c.Collector.Preview().(Signal)
}
